############################################################################
# Contest 2026 team 345 ESP32-P4X Function EV Board
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = board_boot.c

include $(TOPDIR)/boards/Board.mk
