############################################################################
# Contest 2026 team 345 G1 platform smoke test
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = g1_smoke
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_345_G1_SMOKE)

MAINSRC = g1_smoke_main.c

include $(APPDIR)/Application.mk
